version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ..
      dockerfile: Docker/nginx/Dockerfile
    ports:
      - 8080:80
    command: /usr/sbin/nginx -c /etc/nginx/nginx.conf
    environment:
     - LD_LIBRARY_PATH=/usr/local/lib
  charlie:
    container_name: charlie
    build:
      context: ..
      dockerfile: Docker/upstream/Dockerfile
    command: python -m http.server 8090
  django:
    container_name: django
    build:
      context: ..
      dockerfile: Docker/upstream/Dockerfile
    command: python -m http.server 8090 --directory /tmp/
